Fix docs
yiisoft/yii-auth-client pull request #67
Opened 2024-05-08 09:26 UTC by luizcmarin

2024-05-18 17:53 UTC, vjik requested changes

2024-05-18 17:53 UTC, vjik commented on docs/guide/pt-BR/README.md
Translate to pt-BR or remove translation.

2024-05-19 16:31 UTC, luizcmarin commented on docs/guide/pt-BR/README.md
Ok. in progress

2024-05-20 10:35 UTC, vjik approved these changes

2024-05-20 10:35 UTC, merged